import type { Migration } from './migrations';

/**
 * Migrações do PostgreSQL. A versão 1 é o estado final das 13 migrações do
 * SQLite (migrations.ts), já consolidado: o banco PostgreSQL nasce novo, então
 * não há histórico a reproduzir.
 *
 * Diferenças propositais em relação ao SQLite:
 *  - COLLATE NOCASE  -> colunas CITEXT (username, sectors.name), que já comparam
 *    sem diferenciar maiúsculas de minúsculas;
 *  - INTEGER AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY, que aceita
 *    valores explícitos na importação dos dados antigos;
 *  - datas continuam em TEXT no formato ISO-8601 (ex.: 2026-09-21T10:30:00.000Z),
 *    exatamente como no SQLite, para não mudar o comportamento da aplicação;
 *  - campos de sim/não continuam INTEGER 0/1, pelo mesmo motivo.
 *
 * Nunca altere uma migração já aplicada: crie outra com o próximo número.
 */
export const POSTGRES_MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: 'estrutura inicial (equivalente às migrações 1-13 do SQLite)',
    sql: `
      CREATE TABLE users (
        id                   TEXT PRIMARY KEY,
        username             CITEXT NOT NULL UNIQUE,
        name                 TEXT NOT NULL,
        registration         TEXT,
        sector               TEXT,
        shift                TEXT,
        role                 TEXT NOT NULL CHECK (role IN ('ADMIN', 'EMPLOYEE')),
        status               TEXT NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
        password_hash        TEXT NOT NULL,
        created_at           TEXT NOT NULL,
        must_change_password INTEGER NOT NULL DEFAULT 0,
        chat_contact         INTEGER NOT NULL DEFAULT 1,
        super_admin          INTEGER NOT NULL DEFAULT 0
      );
      -- Matrícula única entre funcionários (quem não tem matrícula fica de fora)
      CREATE UNIQUE INDEX idx_users_registration ON users (registration) WHERE registration IS NOT NULL;
      -- Contagem de destinatários por setor/turno
      CREATE INDEX idx_users_role_sector ON users (role, sector);
      CREATE INDEX idx_users_role_shift ON users (role, shift);

      CREATE TABLE computers (
        computer_id        TEXT PRIMARY KEY,
        hostname           TEXT NOT NULL,
        app_version        TEXT NOT NULL,
        platform           TEXT NOT NULL,
        status             TEXT NOT NULL CHECK (status IN ('ONLINE', 'OFFLINE')),
        registered_at      TEXT NOT NULL,
        last_seen_at       TEXT NOT NULL,
        -- Segredo próprio da instalação (hash), exigido nos registros seguintes do mesmo PC
        secret_hash        TEXT,
        -- Funcionário logado agora neste computador
        current_user_id    TEXT REFERENCES users (id),
        current_user_since TEXT
      );
      CREATE INDEX idx_computers_current_user ON computers (current_user_id);

      -- Tokens de acesso (guardamos só o hash SHA-256)
      CREATE TABLE auth_tokens (
        token_hash   TEXT PRIMARY KEY,
        subject_type TEXT NOT NULL CHECK (subject_type IN ('USER', 'COMPUTER')),
        subject_id   TEXT NOT NULL,
        created_at   TEXT NOT NULL,
        expires_at   TEXT
      );
      CREATE INDEX idx_auth_tokens_subject ON auth_tokens (subject_type, subject_id);

      CREATE TABLE sectors (
        id         TEXT PRIMARY KEY,
        name       CITEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL
      );

      CREATE TABLE messages (
        seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title      TEXT NOT NULL,
        content    TEXT NOT NULL,
        type       TEXT NOT NULL,
        target     TEXT NOT NULL,
        target_id  TEXT,
        sender     TEXT NOT NULL,
        created_at TEXT NOT NULL
      );
      CREATE INDEX idx_messages_target ON messages (target, target_id);

      CREATE TABLE message_reads (
        message_seq         BIGINT NOT NULL REFERENCES messages (seq) ON DELETE CASCADE,
        -- Quem leu: o funcionário logado ou, sem login, o próprio PC (PC-...)
        reader_id           TEXT NOT NULL,
        read_at             TEXT NOT NULL,
        -- Em qual computador foi lida (a Central mostra "lida no PC X")
        computer_id         TEXT,
        -- Nome e matrícula de quem leu: excluir o funcionário não apaga o histórico
        reader_name         TEXT,
        reader_registration TEXT,
        PRIMARY KEY (message_seq, reader_id)
      );
      CREATE INDEX idx_message_reads_reader ON message_reads (reader_id);

      -- Conversa entre um funcionário e uma pessoa do DP
      CREATE TABLE chat_messages (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        employee_id TEXT NOT NULL,
        dp_user_id  TEXT,
        sender_type TEXT NOT NULL CHECK (sender_type IN ('DP', 'EMPLOYEE')),
        sender_name TEXT NOT NULL,
        content     TEXT NOT NULL,
        created_at  TEXT NOT NULL,
        -- quando o outro lado leu
        read_at     TEXT,
        -- 1 = enviada pela resposta automática
        automatic   INTEGER NOT NULL DEFAULT 0
      );
      CREATE INDEX idx_chat_employee ON chat_messages (employee_id, id);
      CREATE INDEX idx_chat_conversation ON chat_messages (employee_id, dp_user_id, id);
      CREATE INDEX idx_chat_dp ON chat_messages (dp_user_id, employee_id, id);

      -- Textos que cada pessoa do DP escolhe, por setor do funcionário
      CREATE TABLE auto_replies (
        id         TEXT PRIMARY KEY,
        dp_user_id TEXT NOT NULL,
        sector     TEXT, -- NULL = todos os setores
        content    TEXT NOT NULL,
        active     INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );
      CREATE UNIQUE INDEX idx_auto_replies_sector ON auto_replies (dp_user_id, COALESCE(sector, ''));

      -- Arquivos e imagens dos comunicados; o conteúdo fica em data/uploads/
      CREATE TABLE attachments (
        id          TEXT PRIMARY KEY,
        -- NULL = enviado mas o comunicado ainda não foi criado (some na faxina)
        message_seq BIGINT REFERENCES messages (seq) ON DELETE CASCADE,
        name        TEXT NOT NULL,
        mime_type   TEXT NOT NULL,
        size        INTEGER NOT NULL,
        kind        TEXT NOT NULL CHECK (kind IN ('IMAGE', 'FILE')),
        stored_name TEXT NOT NULL,
        uploaded_by TEXT NOT NULL,
        created_at  TEXT NOT NULL
      );
      CREATE INDEX idx_attachments_message ON attachments (message_seq);
      CREATE INDEX idx_attachments_pending ON attachments (created_at) WHERE message_seq IS NULL;
    `,
  },
  {
    version: 2,
    name: 'mural, mídias, atalhos e foto de perfil',
    sql: `
      -- Imagens e vídeos do mural e fotos de perfil. O arquivo fica em data/midias;
      -- aqui ficam só os dados (nome original, tipo, tamanho, hash).
      CREATE TABLE midias (
        id          TEXT PRIMARY KEY,
        tipo        TEXT NOT NULL CHECK (tipo IN ('IMAGEM', 'VIDEO')),
        nome        TEXT NOT NULL,
        mime_type   TEXT NOT NULL,
        tamanho     BIGINT NOT NULL,
        sha256      TEXT NOT NULL,
        stored_name TEXT NOT NULL,
        enviado_por TEXT NOT NULL,
        created_at  TEXT NOT NULL
      );

      -- Mural: o recado que a Central do DP deixa fixado na tela inicial
      CREATE TABLE mural_posts (
        id         TEXT PRIMARY KEY,
        titulo     TEXT NOT NULL,
        texto      TEXT NOT NULL,
        midia_id   TEXT REFERENCES midias (id) ON DELETE SET NULL,
        ativo      INTEGER NOT NULL DEFAULT 1,
        criado_por TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );
      CREATE INDEX idx_mural_ativo ON mural_posts (ativo, created_at);

      -- Atalhos que cada colaborador monta na tela inicial
      CREATE TABLE atalhos (
        id         TEXT PRIMARY KEY,
        user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        ordem      INTEGER NOT NULL,
        rotulo     TEXT NOT NULL,
        icone      TEXT NOT NULL,
        cor        TEXT NOT NULL,
        destino    TEXT NOT NULL CHECK (destino IN ('COMUNICADOS', 'CHAT', 'PERFIL', 'CONFIGURACOES', 'MURAL')),
        created_at TEXT NOT NULL
      );
      CREATE INDEX idx_atalhos_user ON atalhos (user_id, ordem);

      -- Foto de perfil do colaborador
      ALTER TABLE users ADD COLUMN foto_midia_id TEXT REFERENCES midias (id);
    `,
  },
  {
    version: 3,
    name: 'chamados para o TI',
    sql: `
      -- Chamados abertos para o TI (separados do chat com o DP)
      CREATE TABLE chamados (
        id                TEXT PRIMARY KEY,
        -- número curto, o que as pessoas falam ("chamado 42")
        numero            BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
        titulo            TEXT NOT NULL,
        descricao         TEXT NOT NULL,
        categoria         TEXT NOT NULL CHECK (categoria IN ('COMPUTADOR', 'IMPRESSORA', 'SISTEMA', 'REDE', 'ACESSO', 'OUTRO')),
        prioridade        TEXT NOT NULL CHECK (prioridade IN ('BAIXA', 'NORMAL', 'ALTA')),
        status            TEXT NOT NULL CHECK (status IN ('ABERTO', 'EM_ANDAMENTO', 'RESOLVIDO', 'FECHADO')),
        -- quem abriu: funcionário no app ou pessoa do DP na Central
        solicitante_id    TEXT NOT NULL,
        -- nome guardado junto: excluir o usuário não apaga o histórico do chamado
        solicitante_nome  TEXT NOT NULL,
        -- de qual computador foi aberto (ajuda o TI a achar a máquina)
        computador_id     TEXT,
        -- pessoa do TI que assumiu
        responsavel_id    TEXT,
        responsavel_nome  TEXT,
        created_at        TEXT NOT NULL,
        updated_at        TEXT NOT NULL,
        resolvido_em      TEXT
      );
      CREATE INDEX idx_chamados_status ON chamados (status, created_at);
      CREATE INDEX idx_chamados_solicitante ON chamados (solicitante_id, created_at);

      -- Conversa dentro do chamado
      CREATE TABLE chamado_mensagens (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        chamado_id  TEXT NOT NULL REFERENCES chamados (id) ON DELETE CASCADE,
        autor_id    TEXT NOT NULL,
        autor_nome  TEXT NOT NULL,
        autor_tipo  TEXT NOT NULL CHECK (autor_tipo IN ('SOLICITANTE', 'TI')),
        conteudo    TEXT NOT NULL,
        created_at  TEXT NOT NULL,
        -- quando o outro lado leu
        lida_em     TEXT
      );
      CREATE INDEX idx_chamado_mensagens ON chamado_mensagens (chamado_id, id);

      -- Prints e fotos anexados na abertura do chamado
      CREATE TABLE chamado_midias (
        chamado_id TEXT NOT NULL REFERENCES chamados (id) ON DELETE CASCADE,
        midia_id   TEXT NOT NULL REFERENCES midias (id) ON DELETE CASCADE,
        ordem      INTEGER NOT NULL,
        PRIMARY KEY (chamado_id, midia_id)
      );
    `,
  },
  {
    version: 4,
    name: 'conversas entre pessoas e grupos',
    sql: `
      -- midias passa a aceitar documentos (PDF, Word, Excel) além de imagem e vídeo
      ALTER TABLE midias DROP CONSTRAINT midias_tipo_check;
      ALTER TABLE midias ADD CONSTRAINT midias_tipo_check CHECK (tipo IN ('IMAGEM', 'VIDEO', 'ARQUIVO'));

      -- Conversas: diretas (duas pessoas) ou grupos
      CREATE TABLE conversas (
        id         TEXT PRIMARY KEY,
        tipo       TEXT NOT NULL CHECK (tipo IN ('DIRETA', 'GRUPO')),
        -- só para grupo
        nome       TEXT,
        criado_por TEXT NOT NULL,
        created_at TEXT NOT NULL,
        -- última movimentação: ordena a lista de conversas
        updated_at TEXT NOT NULL
      );
      CREATE INDEX idx_conversas_movimento ON conversas (updated_at);

      -- Quem participa de cada conversa
      CREATE TABLE conversa_membros (
        conversa_id    TEXT NOT NULL REFERENCES conversas (id) ON DELETE CASCADE,
        user_id        TEXT NOT NULL,
        -- ADMIN do grupo: muda o nome e mexe nos participantes
        papel          TEXT NOT NULL CHECK (papel IN ('ADMIN', 'MEMBRO')),
        entrou_em      TEXT NOT NULL,
        -- data da última vez que abriu (conta as não lidas)
        ultima_leitura TEXT,
        -- saiu do grupo: fica no histórico, sem receber mensagem nova
        saiu_em        TEXT,
        PRIMARY KEY (conversa_id, user_id)
      );
      CREATE INDEX idx_conversa_membros_user ON conversa_membros (user_id, saiu_em);

      CREATE TABLE conversa_mensagens (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversa_id TEXT NOT NULL REFERENCES conversas (id) ON DELETE CASCADE,
        autor_id    TEXT NOT NULL,
        -- nome guardado junto: excluir o usuário não apaga o histórico
        autor_nome  TEXT NOT NULL,
        -- SISTEMA: "fulano entrou no grupo", "beltrano saiu"
        tipo        TEXT NOT NULL CHECK (tipo IN ('TEXTO', 'MIDIA', 'SISTEMA')),
        conteudo    TEXT NOT NULL,
        -- imagem, vídeo ou documento anexado
        midia_id    TEXT REFERENCES midias (id),
        -- resposta automática de uma pessoa do DP
        automatica  INTEGER NOT NULL DEFAULT 0,
        created_at  TEXT NOT NULL,
        apagada_em  TEXT
      );
      CREATE INDEX idx_conversa_mensagens ON conversa_mensagens (conversa_id, id);

      -- Registro de quando o TI abre uma conversa (auditoria de quem leu o quê)
      CREATE TABLE conversa_acessos_ti (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversa_id  TEXT NOT NULL,
        usuario_id   TEXT NOT NULL,
        usuario_nome TEXT NOT NULL,
        created_at   TEXT NOT NULL
      );
      CREATE INDEX idx_acessos_ti ON conversa_acessos_ti (conversa_id, created_at);
    `,
  },
  {
    version: 5,
    name: 'chat antigo vira conversa direta',
    sql: `
      -- Traz o chat antigo (par funcionário + pessoa do DP) para o modelo novo.
      -- A tabela chat_messages continua no banco como cópia de segurança.
      CREATE TABLE migra_conversas AS
        SELECT employee_id, dp_user_id,
               'CNV-' || encode(gen_random_bytes(12), 'hex') AS conversa_id,
               MIN(created_at) AS inicio,
               MAX(created_at) AS fim
        FROM chat_messages
        WHERE dp_user_id IS NOT NULL
        GROUP BY employee_id, dp_user_id;

      INSERT INTO conversas (id, tipo, nome, criado_por, created_at, updated_at)
        SELECT conversa_id, 'DIRETA', NULL, employee_id, inicio, fim FROM migra_conversas;

      INSERT INTO conversa_membros (conversa_id, user_id, papel, entrou_em)
        SELECT conversa_id, employee_id, 'MEMBRO', inicio FROM migra_conversas
        UNION ALL
        SELECT conversa_id, dp_user_id, 'MEMBRO', inicio FROM migra_conversas;

      INSERT INTO conversa_mensagens (conversa_id, autor_id, autor_nome, tipo, conteudo, midia_id, automatica, created_at)
        SELECT m.conversa_id,
               CASE WHEN c.sender_type = 'DP' THEN c.dp_user_id ELSE c.employee_id END,
               c.sender_name,
               'TEXTO',
               c.content,
               NULL,
               c.automatic,
               c.created_at
        FROM chat_messages c
        JOIN migra_conversas m ON m.employee_id = c.employee_id AND m.dp_user_id = c.dp_user_id
        ORDER BY c.id;

      -- Leitura aproximada: a última vez que cada lado leu o que o outro escreveu
      UPDATE conversa_membros SET ultima_leitura = (
        SELECT MAX(c.read_at)
        FROM chat_messages c
        JOIN migra_conversas m ON m.employee_id = c.employee_id AND m.dp_user_id = c.dp_user_id
        WHERE m.conversa_id = conversa_membros.conversa_id
          AND c.read_at IS NOT NULL
          AND ((conversa_membros.user_id = c.employee_id AND c.sender_type = 'DP')
            OR (conversa_membros.user_id = c.dp_user_id AND c.sender_type = 'EMPLOYEE'))
      )
      WHERE conversa_id IN (SELECT conversa_id FROM migra_conversas);

      DROP TABLE migra_conversas;
    `,
  },
];
