import type { Migration } from './migrations';

/**
 * Migrações do PostgreSQL. A versão 1 é o estado final das 13 migrações do
 * SQLite (migrations.ts), já consolidado: o banco PostgreSQL nasce novo, então
 * não há histórico a reproduzir.
 *
 * Diferenças propositais em relação ao SQLite:
 *  - COLLATE NOCASE  -> colunas CITEXT (username, sectors.name), que já comparam
 *    sem diferenciar maiúsculas de minúsculas;
 *  - INTEGER AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY, que aceita
 *    valores explícitos na importação dos dados antigos;
 *  - datas continuam em TEXT no formato ISO-8601 (ex.: 2026-09-21T10:30:00.000Z),
 *    exatamente como no SQLite, para não mudar o comportamento da aplicação;
 *  - campos de sim/não continuam INTEGER 0/1, pelo mesmo motivo.
 *
 * Nunca altere uma migração já aplicada: crie outra com o próximo número.
 */
export const POSTGRES_MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: 'estrutura inicial (equivalente às migrações 1-13 do SQLite)',
    sql: `
      CREATE TABLE users (
        id                   TEXT PRIMARY KEY,
        username             CITEXT NOT NULL UNIQUE,
        name                 TEXT NOT NULL,
        registration         TEXT,
        sector               TEXT,
        shift                TEXT,
        role                 TEXT NOT NULL CHECK (role IN ('ADMIN', 'EMPLOYEE')),
        status               TEXT NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
        password_hash        TEXT NOT NULL,
        created_at           TEXT NOT NULL,
        must_change_password INTEGER NOT NULL DEFAULT 0,
        chat_contact         INTEGER NOT NULL DEFAULT 1,
        super_admin          INTEGER NOT NULL DEFAULT 0
      );
      -- Matrícula única entre funcionários (quem não tem matrícula fica de fora)
      CREATE UNIQUE INDEX idx_users_registration ON users (registration) WHERE registration IS NOT NULL;
      -- Contagem de destinatários por setor/turno
      CREATE INDEX idx_users_role_sector ON users (role, sector);
      CREATE INDEX idx_users_role_shift ON users (role, shift);

      CREATE TABLE computers (
        computer_id        TEXT PRIMARY KEY,
        hostname           TEXT NOT NULL,
        app_version        TEXT NOT NULL,
        platform           TEXT NOT NULL,
        status             TEXT NOT NULL CHECK (status IN ('ONLINE', 'OFFLINE')),
        registered_at      TEXT NOT NULL,
        last_seen_at       TEXT NOT NULL,
        -- Segredo próprio da instalação (hash), exigido nos registros seguintes do mesmo PC
        secret_hash        TEXT,
        -- Funcionário logado agora neste computador
        current_user_id    TEXT REFERENCES users (id),
        current_user_since TEXT
      );
      CREATE INDEX idx_computers_current_user ON computers (current_user_id);

      -- Tokens de acesso (guardamos só o hash SHA-256)
      CREATE TABLE auth_tokens (
        token_hash   TEXT PRIMARY KEY,
        subject_type TEXT NOT NULL CHECK (subject_type IN ('USER', 'COMPUTER')),
        subject_id   TEXT NOT NULL,
        created_at   TEXT NOT NULL,
        expires_at   TEXT
      );
      CREATE INDEX idx_auth_tokens_subject ON auth_tokens (subject_type, subject_id);

      CREATE TABLE sectors (
        id         TEXT PRIMARY KEY,
        name       CITEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL
      );

      CREATE TABLE messages (
        seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title      TEXT NOT NULL,
        content    TEXT NOT NULL,
        type       TEXT NOT NULL,
        target     TEXT NOT NULL,
        target_id  TEXT,
        sender     TEXT NOT NULL,
        created_at TEXT NOT NULL
      );
      CREATE INDEX idx_messages_target ON messages (target, target_id);

      CREATE TABLE message_reads (
        message_seq         BIGINT NOT NULL REFERENCES messages (seq) ON DELETE CASCADE,
        -- Quem leu: o funcionário logado ou, sem login, o próprio PC (PC-...)
        reader_id           TEXT NOT NULL,
        read_at             TEXT NOT NULL,
        -- Em qual computador foi lida (a Central mostra "lida no PC X")
        computer_id         TEXT,
        -- Nome e matrícula de quem leu: excluir o funcionário não apaga o histórico
        reader_name         TEXT,
        reader_registration TEXT,
        PRIMARY KEY (message_seq, reader_id)
      );
      CREATE INDEX idx_message_reads_reader ON message_reads (reader_id);

      -- Conversa entre um funcionário e uma pessoa do DP
      CREATE TABLE chat_messages (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        employee_id TEXT NOT NULL,
        dp_user_id  TEXT,
        sender_type TEXT NOT NULL CHECK (sender_type IN ('DP', 'EMPLOYEE')),
        sender_name TEXT NOT NULL,
        content     TEXT NOT NULL,
        created_at  TEXT NOT NULL,
        -- quando o outro lado leu
        read_at     TEXT,
        -- 1 = enviada pela resposta automática
        automatic   INTEGER NOT NULL DEFAULT 0
      );
      CREATE INDEX idx_chat_employee ON chat_messages (employee_id, id);
      CREATE INDEX idx_chat_conversation ON chat_messages (employee_id, dp_user_id, id);
      CREATE INDEX idx_chat_dp ON chat_messages (dp_user_id, employee_id, id);

      -- Textos que cada pessoa do DP escolhe, por setor do funcionário
      CREATE TABLE auto_replies (
        id         TEXT PRIMARY KEY,
        dp_user_id TEXT NOT NULL,
        sector     TEXT, -- NULL = todos os setores
        content    TEXT NOT NULL,
        active     INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );
      CREATE UNIQUE INDEX idx_auto_replies_sector ON auto_replies (dp_user_id, COALESCE(sector, ''));

      -- Arquivos e imagens dos comunicados; o conteúdo fica em data/uploads/
      CREATE TABLE attachments (
        id          TEXT PRIMARY KEY,
        -- NULL = enviado mas o comunicado ainda não foi criado (some na faxina)
        message_seq BIGINT REFERENCES messages (seq) ON DELETE CASCADE,
        name        TEXT NOT NULL,
        mime_type   TEXT NOT NULL,
        size        INTEGER NOT NULL,
        kind        TEXT NOT NULL CHECK (kind IN ('IMAGE', 'FILE')),
        stored_name TEXT NOT NULL,
        uploaded_by TEXT NOT NULL,
        created_at  TEXT NOT NULL
      );
      CREATE INDEX idx_attachments_message ON attachments (message_seq);
      CREATE INDEX idx_attachments_pending ON attachments (created_at) WHERE message_seq IS NULL;
    `,
  },
];
